version: '3'
services:
  node-app:
    build:
      # location of the Dockerfile
      context: . 
      # args will be used in the Dockerfile when building the image. 
      args:
        - NODE_ENV=development
    volumes:
      # Bind mount. Here we can use the dot "." for current directory, no need for ${pwd} that we had to use in docker run command.
      - ./:/app:ro # hostpath:containerpath
      # anonymous volume to not overwrite the node_modules folder. Path is in the container. 
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - MONGO_USER=jonas
      - MONGO_PASSWORD=1234
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jonas
      - MONGO_INITDB_ROOT_PASSWORD=1234
      