version: '3'
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      # location of the Dockerfile
      context: . 
      # args will be used in the Dockerfile when building the image. 
      args:
        - NODE_ENV=production
    environment:
      # ${MONGO_USER} means that the MONGO_USER env var will be pulled from our Ubuntu server env var. 
      # NOTE: This doesn't work. I need to have an .env file with env var in the same folder as compose file. Need to investigate more. 
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}  
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    # This is more optimised than "npm run start".  
    command: node index.js 

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}