version: '3'
# A service is a container. 
services:
  node-app:
    # Build the image from our Dockerfile
    build: . # "." is the path to our Dockerfile. 
    # All the configurations from the docker run command. Port to open, bind mount volume, anonymous volume, env file,  
    ports:
      - "3000:3000"
    environment:
      - Port=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jonas
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      # a named volume with name "mongo-db". 
      - mongo-db:/data/db # nameofvolume:pathincontainer

# A named volume can be used by multiple services. That is why we need to add this.
volumes:
  mongo-db:
